server:
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  mandatory-file-encoding: UTF-8
  profiles:
    active: local # 기본 프로파일을 'local'로 지정
  application:
    name: springBase
  thymeleaf:
    cache: false # 개발 시 템플릿 캐시 끄기 (운영에서는 보통 true)
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

app:
  base-url: http://localhost:3000 # 비밀번호 재설정 링크 등에 사용될 애플리케이션 기본 URL

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.akmz.springBase
  configuration:
    mapUnderscoreToCamelCase: true

# JWT 관련 설정 (프로파일별로 오버라이드 가능)
jwt:
  secret: ${JWT_SECRET_KEY}
  expiration: 3600000 # 1시간
  refresh-expiration: 604800000 # 7일

# FTP 관련 설정
ftp:
  host: ${FTP_HOST}
  port: ${FTP_PORT}
  username: ${FTP_USERNAME}
  password: ${FTP_PASSWORD}
  remote-base-dir: ${FTP_REMOTE_BASE_DIR:/}

# 이메일 관련 설정
spring.mail:
  host: smtp.gmail.com
  port: 587
  username: ${EMAIL_ID}
  password: ${EMAIL_PW}
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
