

INSERT INTO users (USER_NAME, PASSWORD, EMAIL, USE_YN) VALUES ('user', '$2a$12$Ju75hxXXA2D81vXxj3GWSOUf7YoliRdbX.RcNRGfEmFzz2UfDTzpa', 'akmdz@ezione.co.kr', 'Y');
INSERT INTO users (USER_NAME, PASSWORD, EMAIL, USE_YN) VALUES ('admin', '$2a$12$yFszpJFFoBOOn9HgwjHGxeW4exvztGBa75x6X6wWFXnctbu0r.eiu', NULL, 'Y');
INSERT INTO users (USER_NAME, PASSWORD, EMAIL, USE_YN) VALUES ('disabledUser', '$2a$12$Ju75hxXXA2D81vXxj3GWSOUf7YoliRdbX.RcNRGfEmFzz2UfDTzpa', NULL, 'N');

INSERT INTO authorities (USER_NAME, AUTHORITY) VALUES ('user', 'ROLE_USER');
INSERT INTO authorities (USER_NAME, AUTHORITY) VALUES ('user', 'ROLE_stu');
INSERT INTO authorities (USER_NAME, AUTHORITY) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO authorities (USER_NAME, AUTHORITY) VALUES ('disabledUser', 'ROLE_USER');