CREATE TABLE users (
    USER_NAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    REFRESH_TOKEN  VARCHAR(255),
    USE_YN CHAR(1) NOT NULL
);

CREATE TABLE authorities (
    USER_NAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (USER_NAME, AUTHORITY),
    CONSTRAINT fk_authorities_users FOREIGN KEY (USER_NAME) REFERENCES users(USER_NAME)
);
