CREATE TABLE users (
    USER_NAME VARCHAR(50) PRIMARY KEY,
    PASSWORD VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100), -- EMAIL 컬럼 추가
    REFRESH_TOKEN  VARCHAR(255),
    USE_YN CHAR(1) NOT NULL,
    -- 로그인 시도 제한 관련 컬럼 추가
    LOGIN_FAILURE_COUNT INT DEFAULT 0, -- 로그인 실패 횟수 (기본값 0)
    LAST_FAILURE_TIMESTAMP TIMESTAMP -- 마지막 로그인 실패
);

CREATE TABLE authorities (
    USER_NAME VARCHAR(50) NOT NULL,
    AUTHORITY VARCHAR(50) NOT NULL,
    CONSTRAINT pk_authorities PRIMARY KEY (USER_NAME, AUTHORITY),
    CONSTRAINT fk_authorities_users FOREIGN KEY (USER_NAME) REFERENCES users(USER_NAME)
);

CREATE TABLE auth_tokens (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    TOKEN VARCHAR(255) NOT NULL,
    USER_NAME VARCHAR(50) NOT NULL,
    TOKEN_TYPE VARCHAR(50) NOT NULL,
    EXPIRY_DATE TIMESTAMP NOT NULL,
    CREATED_DATE TIMESTAMP NOT NULL,
    USED BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT fk_auth_tokens_users FOREIGN KEY (USER_NAME) REFERENCES users(USER_NAME)
);

-- 첨부파일 묶음 테이블
CREATE TABLE ATTACH (
    ATTACH_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '첨부 고유 ID',
    ATTACH_NAME VARCHAR(255) NOT NULL COMMENT '첨부명 (예: 1번 게시글 첨부파일)',
    CREATOR_ID VARCHAR(100) COMMENT '생성자 ID',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '생성 시간'
);

-- 개별 첨부파일 테이블
CREATE TABLE ATTACH_FILE (
    FILE_ID BIGINT AUTO_INCREMENT PRIMARY KEY COMMENT '파일 고유 ID',
    ATTACH_ID BIGINT NOT NULL COMMENT '소속된 첨부 ID',
    ORIGINAL_FILE_NAME VARCHAR(255) NOT NULL COMMENT '원본 파일명',
    SAVED_FILE_NAME VARCHAR(255) NOT NULL COMMENT '서버에 저장된 실제 파일명',
    FILE_PATH VARCHAR(512) NOT NULL COMMENT '파일 저장 디렉토리 경로',
    FILE_SIZE BIGINT NOT NULL COMMENT '파일 크기 (bytes)',
    UPLOADER_ID VARCHAR(100) COMMENT '업로드한 사용자 ID',
    UPLOADED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '업로드 시간',
    STATUS VARCHAR(50) DEFAULT 'AVAILABLE' COMMENT '파일 상태 (AVAILABLE, DELETED)',
    DELETED_AT TIMESTAMP NULL COMMENT '삭제된 시간',
    FOREIGN KEY (ATTACH_ID) REFERENCES ATTACH(ATTACH_ID) ON DELETE CASCADE
);
