SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE IF EXISTS ATTACH_FILE;
DROP TABLE IF EXISTS ATTACH;
DROP TABLE IF EXISTS auth_tokens;
DROP TABLE IF EXISTS USER_ROLES;
DROP TABLE IF EXISTS ROLE_RESOURCE_MAPPINGS;
DROP TABLE IF EXISTS RESOURCES;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS users;

SET REFERENTIAL_INTEGRITY TRUE;